[tool]
[tool.commitizen]
name = "cz_conventional_commits"
update_changelog_on_bump = true
bump_message = "bump: release $current_version to $new_version [skip-ci]"
version = "12.2.2"
tag_format = "v$version"
version_files = [
    "setup.py",
    "README.md",
]
